# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11ffac7cf5d7ed4401207903124173b6ead2411013ce8c8fd640e23c00aa6b165cc7b748de2bb0e9368050da6bb46445962a31cc3027fa61161c18674372b6c1

test:
  secret_key_base: d866e457e83475603a7ef187fac9da9f5fb060ccad496de6f68f532aec6bcd584bb7c0ad241a085bc917a999708ed9c74d331fc04a6b3c8267a0f3a5cf15b5aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
